// <auto-generated />
using System;
using BoardGame.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoardGame.Api.Migrations
{
    [DbContext(typeof(BoardGameContext))]
    [Migration("20181030082656_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoardGame.Api.Models.BoardGameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("ObjectId");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BoardGame.Api.Models.BoardGameEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<double>("AverageRating");

                    b.Property<string>("BestPlayerCount");

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<int>("MaxPlayers");

                    b.Property<int>("MaxPlaytime");

                    b.Property<int>("MinPlayers");

                    b.Property<int>("MinPlaytime");

                    b.Property<string>("Name");

                    b.Property<int>("ObjectId");

                    b.Property<int>("PlayingTime");

                    b.Property<string>("Thumbnail");

                    b.Property<int>("UsersRated");

                    b.Property<DateTimeOffset>("YearPublished");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new { Id = 1, Age = 0, AverageRating = 0.0, MaxPlayers = 0, MaxPlaytime = 0, MinPlayers = 0, MinPlaytime = 0, Name = "Azul", ObjectId = 0, PlayingTime = 0, UsersRated = 0, YearPublished = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("BoardGame.Api.Models.GameCategoryGameEntry", b =>
                {
                    b.Property<int>("BoardGameCategoryId");

                    b.Property<int>("BoardGameEntryId");

                    b.HasKey("BoardGameCategoryId", "BoardGameEntryId");

                    b.HasIndex("BoardGameEntryId");

                    b.ToTable("GameCategoryGameEntry");
                });

            modelBuilder.Entity("BoardGame.Api.Models.GamePlaySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("Date");

                    b.Property<int>("GameId");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GamePlaySessions");

                    b.HasData(
                        new { Id = 1, Date = new DateTimeOffset(new DateTime(2018, 10, 30, 8, 26, 56, 108, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), GameId = 1 }
                    );
                });

            modelBuilder.Entity("BoardGame.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new { Id = 1, Name = "Tom" },
                        new { Id = 2, Name = "Jon" }
                    );
                });

            modelBuilder.Entity("BoardGame.Api.Models.PlayerRating", b =>
                {
                    b.Property<int>("GamePlaySessionId");

                    b.Property<int>("PlayerId");

                    b.Property<int?>("Rating");

                    b.HasKey("GamePlaySessionId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new { GamePlaySessionId = 1, PlayerId = 1, Rating = 4 }
                    );
                });

            modelBuilder.Entity("BoardGame.Api.Models.GameCategoryGameEntry", b =>
                {
                    b.HasOne("BoardGame.Api.Models.BoardGameCategory", "BoardGameCategory")
                        .WithMany("Games")
                        .HasForeignKey("BoardGameCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BoardGame.Api.Models.BoardGameEntry", "BoardGameEntry")
                        .WithMany("Categories")
                        .HasForeignKey("BoardGameEntryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoardGame.Api.Models.GamePlaySession", b =>
                {
                    b.HasOne("BoardGame.Api.Models.BoardGameEntry", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoardGame.Api.Models.PlayerRating", b =>
                {
                    b.HasOne("BoardGame.Api.Models.GamePlaySession", "GamePlaySession")
                        .WithMany("PlayerRatings")
                        .HasForeignKey("GamePlaySessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BoardGame.Api.Models.Player", "Player")
                        .WithMany("Ratings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
